import { DEMO_SUBREDDIT } from './constants';
import type {
  AuditEvent,
  DailyMetrics,
  DemoScenario,
  ReopenEvent,
  ReviewLockRecord,
  RuntimeProofStatus,
  TargetMetrics,
} from './schema';

const generatedAt = '2026-05-24T00:00:00.000Z';

export const demoLocks: ReviewLockRecord[] = [
  {
    id: 'demo-lock-001',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo001',
    targetKind: 'post',
    targetAuthor: 'u_launch_author',
    permalink: '/r/reviewlock_demo/comments/demo001/policy_context_thread/',
    title: 'Policy context thread',
    contentPreview: 'Moderator-reviewed policy context with repeated stale reports.',
    contentHash: 'hash-demo-001',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_alpha',
    lockedAt: '2026-05-20T09:00:00.000Z',
    lockReason: 'reviewed_policy_compliant',
    status: 'active',
    lastKnownEdited: false,
    lastReportCount: 9,
    suppressedReportCount: 5,
    lastSuppressedAt: '2026-05-20T12:00:00.000Z',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-002',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't1_demo002',
    targetKind: 'comment',
    targetAuthor: 'u_context_helper',
    permalink: '/r/reviewlock_demo/comments/demo001/-/demo002/',
    contentPreview: 'A sourced clarification that has been reviewed by the team.',
    contentHash: 'hash-demo-002',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_beta',
    lockedAt: '2026-05-20T10:30:00.000Z',
    lockReason: 'approved_context_known',
    status: 'active',
    lastKnownEdited: false,
    lastReportCount: 4,
    suppressedReportCount: 2,
    lastSuppressedAt: '2026-05-20T13:00:00.000Z',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-003',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo003',
    targetKind: 'post',
    targetAuthor: 'u_event_host',
    permalink: '/r/reviewlock_demo/comments/demo003/event_logistics/',
    title: 'Event logistics',
    contentPreview: 'A recurring announcement with resolved report churn.',
    contentHash: 'hash-demo-003',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_alpha',
    lockedAt: '2026-05-20T11:00:00.000Z',
    lockReason: 'repeat_report_churn',
    status: 'active',
    lastKnownEdited: false,
    lastReportCount: 6,
    suppressedReportCount: 3,
    lastSuppressedAt: '2026-05-20T16:30:00.000Z',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-004',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't1_demo004',
    targetKind: 'comment',
    targetAuthor: 'u_regular',
    permalink: '/r/reviewlock_demo/comments/demo003/-/demo004/',
    contentPreview: 'Reviewed comment that later stayed unchanged through reports.',
    contentHash: 'hash-demo-004',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_gamma',
    lockedAt: '2026-05-20T11:45:00.000Z',
    lockReason: 'mod_team_consensus',
    status: 'active',
    lastKnownEdited: false,
    lastReportCount: 2,
    suppressedReportCount: 1,
    lastSuppressedAt: '2026-05-20T15:10:00.000Z',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-005',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo005',
    targetKind: 'post',
    targetAuthor: 'u_reviewer',
    permalink: '/r/reviewlock_demo/comments/demo005/resource_index/',
    title: 'Resource index',
    contentPreview: 'Resource list reviewed after context was confirmed.',
    contentHash: 'hash-demo-005',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_beta',
    lockedAt: '2026-05-20T12:05:00.000Z',
    lockReason: 'approved_context_known',
    status: 'active',
    lastKnownEdited: false,
    lastReportCount: 1,
    suppressedReportCount: 0,
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-006',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't1_demo006',
    targetKind: 'comment',
    targetAuthor: 'u_cited_reply',
    permalink: '/r/reviewlock_demo/comments/demo005/-/demo006/',
    contentPreview: 'Reviewed citation reply.',
    contentHash: 'hash-demo-006',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_alpha',
    lockedAt: '2026-05-20T13:15:00.000Z',
    lockReason: 'reviewed_policy_compliant',
    status: 'active',
    lastKnownEdited: false,
    lastReportCount: 1,
    suppressedReportCount: 0,
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-007',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo007',
    targetKind: 'post',
    targetAuthor: 'u_changed_post',
    permalink: '/r/reviewlock_demo/comments/demo007/edited_after_review/',
    title: 'Edited after review',
    contentPreview: 'Original body was reviewed, then the author edited material details.',
    contentHash: 'hash-demo-007-old',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_delta',
    lockedAt: '2026-05-20T14:00:00.000Z',
    lockReason: 'reviewed_policy_compliant',
    status: 'reopened',
    lastKnownEdited: true,
    lastReportCount: 7,
    suppressedReportCount: 2,
    lastSuppressedAt: '2026-05-20T15:00:00.000Z',
    reopenedAt: '2026-05-20T17:20:00.000Z',
    reopenReason: 'content_changed',
    reopenEventId: 'demo-reopen-001',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-008',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't1_demo008',
    targetKind: 'comment',
    targetAuthor: 'u_comment_editor',
    permalink: '/r/reviewlock_demo/comments/demo007/-/demo008/',
    contentPreview: 'Comment changed after lock and returned to moderator attention.',
    contentHash: 'hash-demo-008-old',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_beta',
    lockedAt: '2026-05-20T14:30:00.000Z',
    lockReason: 'mod_team_consensus',
    status: 'reopened',
    lastKnownEdited: true,
    lastReportCount: 3,
    suppressedReportCount: 1,
    lastSuppressedAt: '2026-05-20T14:50:00.000Z',
    reopenedAt: '2026-05-20T18:00:00.000Z',
    reopenReason: 'content_changed',
    reopenEventId: 'demo-reopen-002',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-009',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo009',
    targetKind: 'post',
    targetAuthor: 'u_flair_editor',
    permalink: '/r/reviewlock_demo/comments/demo009/flair_changed_after_review/',
    title: 'Flair changed after review',
    contentPreview: 'Post flair changed after approval, so the lock reopened.',
    contentHash: 'hash-demo-009-old',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_gamma',
    lockedAt: '2026-05-20T15:00:00.000Z',
    lockReason: 'approved_context_known',
    status: 'reopened',
    lastKnownEdited: false,
    lastReportCount: 5,
    suppressedReportCount: 2,
    lastSuppressedAt: '2026-05-20T15:45:00.000Z',
    reopenedAt: '2026-05-20T18:10:00.000Z',
    reopenReason: 'flair_changed',
    reopenEventId: 'demo-reopen-003',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-010',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo010',
    targetKind: 'post',
    targetAuthor: 'u_warning_case',
    permalink: '/r/reviewlock_demo/comments/demo010/runtime_warning_example/',
    title: 'Runtime warning example',
    contentPreview: 'A lock with a simulated runtime warning for honest dashboard status.',
    contentHash: 'hash-demo-010',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_delta',
    lockedAt: '2026-05-20T15:30:00.000Z',
    lockReason: 'custom',
    customNote: 'Demo warning case.',
    status: 'failed',
    lastKnownEdited: false,
    lastReportCount: 1,
    suppressedReportCount: 0,
    runtimeWarnings: ['ignoreReports capability failed in seeded runtime example'],
    demo: true,
  },
  {
    id: 'demo-lock-011',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't1_demo011',
    targetKind: 'comment',
    targetAuthor: 'u_report_target',
    permalink: '/r/reviewlock_demo/comments/demo010/-/demo011/',
    contentPreview: 'Low-volume reviewed comment.',
    contentHash: 'hash-demo-011',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_alpha',
    lockedAt: '2026-05-20T16:00:00.000Z',
    lockReason: 'reviewed_policy_compliant',
    status: 'active',
    lastKnownEdited: false,
    lastReportCount: 0,
    suppressedReportCount: 0,
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-lock-012',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo012',
    targetKind: 'post',
    targetAuthor: 'u_question_author',
    permalink: '/r/reviewlock_demo/comments/demo012/question_megathread/',
    title: 'Question megathread',
    contentPreview: 'Reviewed recurring megathread with one stale report suppressed.',
    contentHash: 'hash-demo-012',
    fingerprintVersion: 'content-v1',
    lockedBy: 'mod_beta',
    lockedAt: '2026-05-20T16:20:00.000Z',
    lockReason: 'repeat_report_churn',
    status: 'active',
    lastKnownEdited: false,
    lastReportCount: 2,
    suppressedReportCount: 1,
    lastSuppressedAt: '2026-05-20T16:50:00.000Z',
    runtimeWarnings: [],
    demo: true,
  },
];

export const demoReopenEvents: ReopenEvent[] = [
  {
    id: 'demo-reopen-001',
    lockId: 'demo-lock-007',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo007',
    targetKind: 'post',
    oldContentHash: 'hash-demo-007-old',
    newContentHash: 'hash-demo-007-new',
    reason: 'content_changed',
    createdAt: '2026-05-20T17:20:00.000Z',
    summary: 'Post body changed after moderator review.',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-reopen-002',
    lockId: 'demo-lock-008',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't1_demo008',
    targetKind: 'comment',
    oldContentHash: 'hash-demo-008-old',
    newContentHash: 'hash-demo-008-new',
    reason: 'content_changed',
    createdAt: '2026-05-20T18:00:00.000Z',
    summary: 'Comment body changed after moderator review.',
    runtimeWarnings: [],
    demo: true,
  },
  {
    id: 'demo-reopen-003',
    lockId: 'demo-lock-009',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo009',
    targetKind: 'post',
    oldContentHash: 'hash-demo-009-old',
    newContentHash: 'hash-demo-009-new',
    reason: 'flair_changed',
    createdAt: '2026-05-20T18:10:00.000Z',
    summary: 'Post flair changed after moderator review.',
    runtimeWarnings: [],
    demo: true,
  },
];

export const demoAuditEvents: AuditEvent[] = [
  {
    id: 'demo-audit-001',
    kind: 'lock_created',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo001',
    targetKind: 'post',
    lockId: 'demo-lock-001',
    actor: 'mod_alpha',
    createdAt: '2026-05-20T09:00:00.000Z',
    message: 'Reviewed post locked until content changes.',
    data: { beat: 'lock' },
    demo: true,
  },
  {
    id: 'demo-audit-002',
    kind: 'report_suppressed',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo001',
    targetKind: 'post',
    lockId: 'demo-lock-001',
    actor: 'reviewlock',
    createdAt: '2026-05-20T12:00:00.000Z',
    message: 'Repeat reports suppressed after fingerprint matched.',
    data: { beat: 'reports_suppressed', count: 5 },
    demo: true,
  },
  {
    id: 'demo-audit-003',
    kind: 'lock_reopened',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo007',
    targetKind: 'post',
    lockId: 'demo-lock-007',
    actor: 'reviewlock',
    createdAt: '2026-05-20T17:20:00.000Z',
    message: 'Post edit changed the fingerprint and reopened the lock.',
    data: { beat: 'edit', reason: 'content_changed' },
    demo: true,
  },
  {
    id: 'demo-audit-004',
    kind: 'lock_reopened',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't1_demo008',
    targetKind: 'comment',
    lockId: 'demo-lock-008',
    actor: 'reviewlock',
    createdAt: '2026-05-20T18:00:00.000Z',
    message: 'Comment edit changed the fingerprint and reopened the lock.',
    data: { beat: 'reopen', reason: 'content_changed' },
    demo: true,
  },
  {
    id: 'demo-audit-005',
    kind: 'runtime_failure',
    subreddit: DEMO_SUBREDDIT,
    targetId: 't3_demo010',
    targetKind: 'post',
    lockId: 'demo-lock-010',
    actor: 'reviewlock',
    createdAt: '2026-05-20T15:31:00.000Z',
    message: 'Demo runtime warning recorded for capability transparency.',
    data: { operation: 'ignoreReports', ok: false },
    demo: true,
  },
];

export const demoDailyMetrics: DailyMetrics[] = [
  {
    subreddit: DEMO_SUBREDDIT,
    date: '2026-05-20',
    locksCreated: 12,
    reportsSuppressed: 17,
    locksReopened: 3,
    demo: true,
  },
];

export const demoTargetMetrics: TargetMetrics[] = demoLocks.map((lock) => ({
  subreddit: lock.subreddit,
  targetId: lock.targetId,
  targetKind: lock.targetKind,
  reportsSuppressed: lock.suppressedReportCount,
  locksCreated: 1,
  locksReopened: lock.status === 'reopened' ? 1 : 0,
  lastActivityAt: lock.reopenedAt ?? lock.lastSuppressedAt ?? lock.lockedAt,
  demo: true,
}));

export const demoRuntimeStatus: RuntimeProofStatus = {
  overall: 'unverified',
  generatedAt,
  capabilities: [
    {
      name: 'approve',
      status: 'unverified',
      notes: ['Implemented capability will require Wave 13 playtest proof.'],
    },
    {
      name: 'ignoreReports',
      status: 'unverified',
      notes: ['Demo includes a warning example so runtime uncertainty stays visible.'],
    },
    {
      name: 'unignoreReports',
      status: 'unverified',
      notes: ['Reopen path will be tested before live claims are made.'],
    },
  ],
  warnings: ['Demo data only. Live Devvit behavior is not verified in Wave 02.'],
};

export const DEMO_SCENARIO: DemoScenario = {
  subreddit: DEMO_SUBREDDIT,
  generatedAt,
  label: 'Demo data: lock, repeat reports, edit, reopen',
  locks: demoLocks,
  reopenEvents: demoReopenEvents,
  auditEvents: demoAuditEvents,
  dailyMetrics: demoDailyMetrics,
  targetMetrics: demoTargetMetrics,
  runtimeStatus: demoRuntimeStatus,
};
